export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const IS_SHOW_HUMBERG_MENU = 'IS_SHOW_HUMBERG_MENU'

export const SET_SD_MASTER_DATA = 'SET_SD_MASTER_DATA'
export const RESET_SD_MASTER_DATA = 'RESET_SD_MASTER_DATA'

export const SEARCH_RESULT = 'SEARCH_RESULT'
export const RESET_SEARCH_RESULT = 'RESET_SEARCH_RESULT'
export const PAGE_TITLE = "PAGE_TITLE"

export const PAGE_ACTIVE = "PAGE_ACTIVE"

export const SET_ADDITIONAL_INFORMATION = 'SET_ADDITIONAL_INFORMATION'

export const SET_CUSTOMER_INFO_MODAL = 'SET_CUSTOMER_INFO_MODAL'

export const SET_ADDRESS = 'SET_ADDRESS'